name: example
description: Gernerate model class from Json files.
version: 0.0.1
author: chuanci <chuanci@vip.qq.com>
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
dev_dependencies:
  build_runner: ^1.10.3
  json_serializable: ^3.5.0
  fson:
    path: ../

