name: example
description: Gernerate model class from Json files.
version: 0.0.1
author: chuanci <chuanci@vip.qq.com>
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  wings_extensions: ^0.0.2
dev_dependencies:
  build_runner: ^1.10.7
  json_serializable: ^3.5.1
  fson:
    path: ../

