name: example
description: Gernerate model class from Json files.
version: 0.0.2
author: chuanci <chuanci@vip.qq.com>
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  build_runner: ^1.10.0
  json_serializable: ^3.3.0
