name: fson
description: Gernerating Dart model class from Json file.
version: 0.5.2
author: chuanci <chuanci@vip.qq.com>
homepage: https://github.com/chuanci/fson

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  args: 1.6.0
  build: 1.2.2
  glob: 1.2.0
  logging: 0.11.4
  io: 0.3.3
  build_resolvers: 1.3.3
  build_runner_core: 4.5.2
  build_runner: 1.8.0
  json_annotation: 3.0.1
  json_serializable: 3.2.5
  path: 1.6.4
  _fe_analyzer_shared: ^3.0.0  # temporary, see https://github.com/dart-lang/sdk/issues/42163

dev_dependencies:

executables:
  fson: