name: fson
description: Gernerating Dart model class from Json file.
version: 1.0.7
author: chuanci <chuanci@vip.qq.com>
homepage: https://github.com/chuanci/fson

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  args: 1.6.0
  process_run: ^0.11.2+6
  mustache_template: ^1.0.0+1
  path: 1.6.4
  wings_extensions: ^0.0.2

#dev_dependencies:

executables:
  fson: