name: fson
description: Gernerating Dart model class from Json file.
version: 1.0.8
author: chuanci <chuanci@vip.qq.com>
homepage: https://github.com/chuanci/fson

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.1.0
  process_run: ^0.12.1
  mustache_template: ^2.0.0
  path: ^1.8.0
  wings_extensions: ^0.1.0

#dev_dependencies:

executables:
  fson: